apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-lb
  labels:
    app: {{ .Values.label.name }}
  namespace: {{ .Values.container.namespace }}
spec:
  selector:
    type: LoadBalancer
    app: {{ .Values.container.Name }}
  ports:
    protocol  : TCP
    port      : 80 #Port on LoadBalancer
    targetPort: 80 #Port on POD
  

