apphost: k8s
label:
  name: petclinic

container:
  image: ekimkuznetsov/petclinic
  name: petclinic
  pullPolicy: Always
  namespace: default
  tagversion: latest
  secret_file: dockerhubsecret


replicaCount: 1
