--- 
- name: "Authentication to GCP"
  command: gcloud auth login --cred-file="{{ service_account_file }}" 
        
- name: "kubeconfig formation"
  command: gcloud container clusters get-credentials "{{ cluster_name }}"
      
- name: "Creation of dockercfg secret "
  command: kubectl create secret docker-registry dockerhubsecret --docker-server="{{DOCKER_REGISTRY_SERVER}}" --docker-username="{{DOCKER_USER}}" --docker-password="{{DOCKER_PASSWORD}}" --docker-email="{{DOCKER_EMAIL}}"
        
- name: Create a Deployment by reading the definition from a local file
  command: kubectl apply -f "{{ deployment_path }}"
