- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-registry
    state: latest

- name: Install pip
  ansible.builtin.apt:
    name: 
      - python3-pip
    state: present

- name: Change privilege of docker
  become: true
  file: dest=/usr/bin/docker mode=+x

- name: python docker / docker-compse module
  pip:
    name:
        - docker

- name: enable docker service
  become: true
  service:
    name: docker
    enabled: yes

- name: Start service
  become: true
  service:
    name: docker
    state: started
