- name: installing jdk
  ansible.builtin.apt:
    name:
      - default-jdk
    state: present

- name: install maven (and other packages if needed)
  become: true
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven